esphome:
  name: ir_remote
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.1.125
    gateway: 192.168.1.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ir Remote Fallback Hotspot"
    password: "XfR8htnrclIC"

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  password: "12345"

ota:
  password: "12345"

sensor:

  - platform: dht
    pin: D5
    temperature:
      name: "DHT Temperature"
      accuracy_decimals: 2
      id: roomtemp
    humidity:
      name: "DHT Humidity"
      accuracy_decimals: 2
    model: DHT22  
    update_interval: 60s
   
  - platform: wifi_signal
    name: "IR Remote WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    name: "IR Remote uptime"
    
switch:
  - platform: restart
    name: "IR Remote restart"

remote_receiver:
  id: rcvr
  pin:
    number: GPIO12
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 55 

remote_transmitter:
  pin: RX
  carrier_duty_percent: 50%

climate:
  - platform: coolix
    name: "Living Room AC"
    sensor: roomtemp          #сенсор показывающий текущую температуру
    receiver_id: rcvr         #фотоприемник
    


  