esphome:
  name: light_room2
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.1.122
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
  ap:
    ssid: Room2
    password: room12345
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: lll2
  reboot_timeout: 0s

ota:
  password: lll2

status_led:
  pin: 
    number: GPIO0
    inverted: True



output:
  - platform: gpio
    pin: GPIO13
    id: light_1g_relay
  - platform: gpio
    pin: GPIO14
    id: light_2g_relay
    
switch:
  - platform: gpio
    name: blue_led
    pin: GPIO16
    id: blue_led
    
  - platform: restart
    name: "Child Room restart"


light:
  - platform: binary
    name: 'light_1g_relay'
    id: light_mt_1g_relay
    output: light_1g_relay
    restore_mode: ALWAYS_OFF
  - platform: binary
    name: 'light_2g_relay'
    id: light_mt_2g_relay
    output: light_2g_relay
    restore_mode: ALWAYS_OFF  


binary_sensor:
  - platform: gpio
    pin: GPIO12
    filters:
      - invert:
      - delayed_on: 20ms
    name: light_1g_button
    id: light_1g_button
    on_release:
      then:
        - light.toggle: light_mt_1g_relay
  - platform: gpio
    pin: GPIO3
    filters:
      - invert:
      - delayed_on: 20ms
    name: light_2g_button
    id: light_2g_button
    on_release:
      then:
        - light.toggle: light_mt_2g_relay      
        
        
sensor:  
  - platform: wifi_signal
    name: "Child Room WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    id: device_uptime
    internal: true
#    name: "Meteostation uptime"

  - platform: ntc
    sensor: resistance_sensor
    calibration:
      b_constant: 3950
      reference_temperature: 25°C
      reference_resistance: 10kOhm
    filters:
      - median:
          window_size: 6
          send_every: 4
          send_first_at: 2  
    name: NTC Temperature

  # Example source sensors:
  - platform: resistance
    id: resistance_sensor
    sensor: source_sensor
    configuration: DOWNSTREAM
    resistor: 47kOhm
    reference_voltage: 3.18
    name: Resistance Sensor
    internal: true
  - platform: adc
    id: source_sensor
    pin: A0
    internal: true
    
text_sensor:

  - platform: template
    name: "Child room uptime"
    lambda: |-
      uint32_t uptime = (id(device_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
        return { (String(minutes) + " мин.").c_str() };
      }
    update_interval: 60s
    icon: mdi:clock-start



