esphome:
  name: light_room1
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  manual_ip:
    static_ip: 192.168.1.123
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    
  ap:
    ssid: Room1
    password: room12345
    
captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: lll1
  reboot_timeout: 0s

ota:
  password: lll1

status_led:
  pin: 
    number: GPIO0
    inverted: True


output:
  - platform: gpio
    pin: GPIO4
    id: light_1g_relay
  
    
switch:
  - platform: gpio
    name: blue_led
    pin: GPIO16
    id: blue_led
    
  - platform: restart
    name: "Living Room restart"

           


light:
  - platform: binary
    name: 'light_1g_relay'
    id: light_mt_1g_relay
    output: light_1g_relay
    restore_mode: ALWAYS_OFF


binary_sensor:
  - platform: gpio
    pin: GPIO3
    filters:
      - invert:
      - delayed_on: 20ms
    name: light_1g_button
    id: light_1g_button
    on_release:
      then:
        - light.toggle: light_mt_1g_relay
        

        
#remote_receiver:
#  pin:
#    number: GPIO2
#    inverted: true
#  dump: rc_switch
#  tolerance: 50%
#  filter: 250us
#  idle: 4ms
#  buffer_size: 2kb
  
sensor:  
  - platform: wifi_signal
    name: "Living Room WiFi Signal"
    update_interval: 60s
    
  - platform: uptime
    id: device_uptime
    internal: true
#    name: "Living Room uptime"

text_sensor:

  - platform: template
    name: "Living Room uptime"
    lambda: |-
      uint32_t uptime = (id(device_uptime).state);
      int minutes = (uptime % 3600) / 60;
      int hours = (uptime % 86400) / 3600;
      int days = uptime / 86400;
      if (days > 0) {
        return { (String(days) + " д." + String(hours) + " ч." + String(minutes) + " мин.").c_str() };
      }
      if (hours > 0) {
        return { (String(hours) + " ч. " + String(minutes) + " мин.").c_str() };
      } else {
        return { (String(minutes) + " мин.").c_str() };
      }
    update_interval: 60s
    icon: mdi:clock-start
    


